// const allRepos = [
//   "chiraag-kakar/createnshare",
//   "niloysikdar/Get-Set-Go",
//   "niloysikdar/Kahani",
//   "niloysikdar/CFI-JGEC",
//   "maityamit/Tracky-Track-your-goals-or-targets",
//   "Kajal13081/Musgenix",
//   "Kajal13081/Gallery-Application",
//   "harshita2216/hello-jobs",
//   "Ly0kami/QuotesApp-JWoC",
//   "theblockchainchief/web3-hub",
//   "BRAVO68WEB/url-minify",
//   "HITK-TECH-Community/Community-Website",
//   "The-Shivam-garg/BigB-E-learn-Websit-e",
//   "Codehackerone/Medify",
//   "aman34503/Go-Airbnb",
//   "SauravMukherjee44/Aec-Library-Website",
//   "riyajha2305/Instagram-Clone",
//   "SaraswatGit/PlanZap",
//   "abhisheks008/ML-Crate",
//   "opticSquid/hive",
//   "gdscjgec/Image-Editor",
//   "prathimacode-hub/Treksy",
//   "gdscjgec/Pictionary",
//   "prathimacode-hub/MedFlare",
//   "ZiaCodes/counter.js",
//   "ZiaCodes/claim-prize",
//   "shibam-naskar/wally",
//   "harshita214/Chrome-Extension",
//   "imniladri/DevHub",
//   "skpandey885/HealhUb",
//   "sahilsaha7773/SpotLight",
//   "shibam-naskar/IMAGE_COMPRESOR",
//   "mohit200008/medi-Care",
//   "HackClubRAIT/HackClubRAIT-Website.github.io",
//   "Saup21/Code-Sandbox",
//   "agamjotsingh18/pollitup",
//   "neelshah2409/Bot-Collection",
//   "BlueBlaze6335/Illicit-Illustrations",
//   "codejay411/Fake-News-Detection-App",
//   "sagnik1511/Tabular-AutoML",
//   "Tech-N-Science/FunwithScience",
//   "smaranjitghose/awesome-portfolio-websites",
//   "IAmTamal/Milan",
//   "smaranjitghose/indokhaadyam",
//   "7saikat7/supply_chain",
// ];

// module.exports = { allRepos };

const allRepos = [
  'anand-harsh/Edumi',
'abhisheks008/ML-Crate',
'Sriparno08/Openpedia',
'Rakesh9100/Click-The-Edible-Game',
'Photon3009/Auberge',
'Rakesh9100/Beautiify',
'Rakesh9100/CalcDiverse',
'JiyaGupta-cs/mytwit',
'janvi01/sql-editor',
'apu52/Travel_Website',
'harmeetsingh11/RefactorMate',
'Pankaj0038/dcodeKi',
'Priyanshi662/FunFusion',
'Priyanshi662/discussion-forum',
'RishabhJain0721/Brain-Box',
'sayakongit/sangnet',
'sayandippaul/dropling-jwoc',
'sayandippaul/IRIS-Smart-Tutor',
'Arbtrage/Enigma',
'hexronuspi/eagleview',
'sayan404/TaskPulse',
'Avdhesh-Varshney/WebMasterLog',
'codervivek5/vigyBag',
'Abhigyan103/Animu',
'pooranjoyb/StoryBook-RN',
'Animesh606/WeatherForcasting',
'Abhigyan103/Clickboard',
'JiyaGupta-cs/ShopNex',
'milancommunity/Milan',
'milancommunity/Milan-Backend',
'tanmoy27112000/flutter_web_base',
'akshitagupta15june/Moksh',
'akshitagupta15june/PetMe',
'akshitagupta15june/Face-X',
'Shreya111111/CodeScribe',
'zakhaev26/WatchDog',
'nitishkumar333/Club-Management',
'sd012gfhkhhvh/Slate.AI',
'neokd/NeoGPT',
'Jagroop2001/validify-string',
'Jagroop2001/AcmeRockets',
'ritika728/Wellness_Wave',
'swarnade/webdesign-switch',
'02shreyansh/CODSOFT',
'psykat1116/Modern_Periodic_Table',
'Ritwika-14/CoupEarn',
'ATLAS2002/resonatejs',
'firtysh/ubuntu_desktop_env',
'Swadeshit27/Admin-panel-frontend',
'Spandan-Bhattacharya/Solve_it']

module.exports = {allRepos}